# PANDAS
Pandas is a powerful open-source Python library used for data analysis and data manipulation.
## Why Pandas is used?

It helps:

- Work with large datasets
- Handle missing data
- Perform data cleaning
- Analyze data quickly
- Read/write data from files (CSV, Excel, etc.)

In [1]:
# install and import library
import numpy as np
import pandas as pd

## Main Data Structures in Pandas

### 1. Series
- One-dimensional (like a single column)
- Example: list of marks

### 2. DataFrame
- Two-dimensional (like a table with rows and columns)
- Example: student records table

### Creating Series

In [28]:
#Using List
#string without index
city=['Sialkot', 'LAhore', 'Gujranwala', 'Daska']
city=pd.Series(city)
city.iloc[0]

'Sialkot'

In [20]:
# integers with index
number=[1,2,3,4]
data1=pd.Series(number, index=['a','b','c','d'])
data1

a    1
b    2
c    3
d    4
dtype: int64

In [23]:
data1[0]

C:\Users\AR\AppData\Local\Temp\ipykernel_3660\2173208830.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data1[0]

np.int64(1)

In [32]:
data1.loc['a']

np.int64(1)

In [ ]:
num=np.range(3),

In [33]:
#Series using dict
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}
data2=pd.Series(marks)
data2

maths       67
english     57
science     89
hindi      100
dtype: int64

In [34]:
data2.loc['hindi']

np.int64(100)

In [37]:
data2.iloc[3]

np.int64(100)

### Creating DataFrame

In [40]:
# using lists
student_data = [
    [100,80,90],
    [90,70,70],
    [80,100,95],
    [80,50,70]
]

pd.DataFrame(student_data, columns=['English','Science','Math'], index=['a','b','c','d'])

   English  Science  Math
a      100       80    90
b       90       70    70
c       80      100    95
d       80       50    70

In [41]:
# using dicts

student_dict = {
    'Name':['Sara','Ayesha','Rabia','Arooj'],
    'English':[100,90,80,80],
    'Science':[80,70,100,50],
    'Math':[90,70,95, 70]
}

students_rec = pd.DataFrame(student_dict)
students_rec

     Name  English  Science  Math
0    Sara      100       80    90
1  Ayesha       90       70    70
2   Rabia       80      100    95
3   Arooj       80       50    70

In [43]:
# using read_csv
diabetes=pd.read_csv('diabetes.csv')

In [44]:
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

### DataFrame Attributes and Methods

In [45]:
# shape
diabetes.shape

(768, 9)

In [46]:
# dtypes
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [47]:
# index
diabetes.index

RangeIndex(start=0, stop=768, step=1)

In [48]:
# columns
diabetes.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [49]:
# values
diabetes.values

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

In [51]:
# head and tail
diabetes.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [53]:
diabetes.tail(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [54]:
# sample
diabetes.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
441,2,83,66,23,50,32.2,0.497,22,0
28,13,145,82,19,110,22.2,0.245,57,0
469,6,154,78,41,140,46.1,0.571,27,0
289,5,108,72,43,75,36.1,0.263,33,0
373,2,105,58,40,94,34.9,0.225,25,0

In [55]:
# info
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [56]:
# describe
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [58]:
# isnull
diabetes.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [63]:
# duplicated
diabetes.duplicated().sum()

np.int64(0)

### Math Methods

In [64]:
# sum -> axis argument
diabetes.sum(axis=0)

Pregnancies                  2953.000
Glucose                     92847.000
BloodPressure               53073.000
SkinThickness               15772.000
Insulin                     61286.000
BMI                         24570.300
DiabetesPedigreeFunction      362.401
Age                         25529.000
Outcome                       268.000
dtype: float64

In [65]:
diabetes.mean(axis=1)

0      38.469667
1      26.550111
2      34.663556
3      35.807444
4      51.043111
         ...
763    56.785667
764    31.682222
765    43.271667
766    29.494333
767    27.635000
Length: 768, dtype: float64

### Selecting cols from a DataFrame

In [66]:
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [67]:
# single cols
diabetes['BloodPressure']

0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64

In [69]:
# multiple cols
diabetes[['BloodPressure', 'Age']]

     BloodPressure  Age
0               72   50
1               66   31
2               64   32
3               66   21
4               40   33
..             ...  ...
763             76   63
764             70   27
765             72   30
766             60   47
767             70   23

[768 rows x 2 columns]

### Selecting rows from a DataFrame

- **iloc** - searches using index positions
- **loc** - searches using index labels

In [70]:
# single row
diabetes.iloc[2]

Pregnancies                   8.000
Glucose                     183.000
BloodPressure                64.000
SkinThickness                 0.000
Insulin                       0.000
BMI                          23.300
DiabetesPedigreeFunction      0.672
Age                          32.000
Outcome                       1.000
Name: 2, dtype: float64

In [71]:
# multiple row
diabetes.iloc[[1,3,5,7]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0

In [ ]:
# fancy indexing

In [ ]:
# loc

### Selecting both rows and cols

# Filtering with Pandas

In [75]:
diabetes['Outcome']

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [78]:
result=diabetes['Outcome']==1

In [79]:
diabetes[result]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [81]:
diabetes[(diabetes['Age']>50 )& (diabetes['Outcome']==1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
24,11,143,94,33,146,36.6,0.254,51,1
39,4,111,72,47,207,37.1,1.390,56,1
43,9,171,110,24,240,45.4,0.721,54,1
53,8,176,90,34,300,33.7,0.467,58,1
93,4,134,72,0,0,23.8,0.277,60,1
115,4,146,92,0,0,31.2,0.539,61,1
129,0,105,84,0,0,27.9,0.741,62,1
186,8,181,68,36,495,30.1,0.615,60,1
206,8,196,76,29,280,37.5,0.605,57,1
207,5,162,104,0,0,37.7,0.151,52,1
221,2,158,90,0,0,31.6,0.805,66,1
236,7,181,84,21,192,35.9,0.586,51,1
259,11,155,76,28,150,33.3,1.353,51,1
284,2,108,80,0,0,27.0,0.259,52,1
319,6,194,78,0,0,23.5,0.129,59,1
363,4,146,78,0,0,38.5,0.520,67,1
375,12,140,82,43,325,39.2,0.528,58,1
388,5,144,82,26,285,32.0,0.452,58,1
458,10,148,84,48,237,37.6,1.001,51,1
498,7,195,70,33,145,25.1,0.163,55,1
516,9,145,88,34,165,30.3,0.771,53,1
542,10,90,85,32,0,34.9,0.825,56,1
546,5,187,76,27,207,43.6,1.034,53,1
560,6,125,76,0,0,33.8,0.121,54,1
579,2,197,70,99,0,34.7,0.575,62,1
584,8,124,76,24,600,28.7,0.687,52,1
588,3,176,86,27,156,33.3,1.154,52,1
603,7,150,78,29,126,35.2,0.692,54,1
666,4,145,82,18,0,32.5,0.235,70,1
676,9,156,86,0,0,24.8,0.230,53,1
702,1,168,88,29,0,35.0,0.905,52,1
719,5,97,76,27,0,35.6,0.378,52,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1